#!/usr/bin/env node
import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {mkdtemp,readFile,writeFile,mkdir,symlink,rm,cp,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
const repo=process.cwd(),binary=path.join(repo,'target/debug/presmith'),runtime=path.join(repo,'examples/product/tooling/renderer');
process.env.PLAYWRIGHT_BROWSERS_PATH=path.join(runtime,'.browsers');
const require=createRequire(path.join(runtime,'package.json'));const {chromium}=require('playwright'),JSZip=require('jszip'),{PDFDocument}=require('pdf-lib');
process.env.PLAYWRIGHT_BROWSERS_PATH=path.join(runtime,'.browsers');
const temp=await mkdtemp(path.join(tmpdir(),'presmith-editor-')),project=path.join(temp,'deck'),screens=path.join(repo,'verification/editor');await mkdir(screens,{recursive:true});
const children=[];let browser,debugPage;const results=[];const pause=ms=>new Promise(r=>setTimeout(r,ms));
function run(args){return JSON.parse(execFileSync(binary,args,{encoding:'utf8'}));}
async function start(dir,command='edit'){
 const child=spawn(binary,[command,dir,'--port','0'],{stdio:['ignore','pipe','pipe']});children.push(child);let log='';child.stderr.on('data',d=>log+=d);
 for(let i=0;i<150&&!log.includes(command==='edit'?'Editor:':'Preview:');i++){if(child.exitCode!==null)throw Error(log);await pause(100);}
 const url=log.match(/http:\/\/127\.0\.0\.1:\d+\/[^\s]*/)?.[0];assert.ok(url,log);return {child,url,token:new URL(url).hash.slice(9),origin:new URL(url).origin};
}
async function test(name,fn){await fn();results.push(name);console.log('PASS '+name);}
try{
 execFileSync(binary,['init',project]);for(const n of ['node_modules','.browsers'])await symlink(path.join(runtime,n),path.join(project,'tooling/renderer',n),'dir');
 const original=await readFile(path.join(project,'slides/intro.html'),'utf8');const untouched=await readFile(path.join(project,'slides/next.html'));const script=await readFile(path.join(project,'scripts/custom.js'));
 const fixture=`\n<div data-element-id="positioned" class="editor-fixture">Move me</div><img data-element-id="photo" class="editor-photo" src="assets/photo.png" alt="Old image"><div data-element-id="grid" class="editor-grid"><p data-element-id="nested">Nested target</p></div><p data-element-id="blocked" class="editor-blocked">Specificity</p><p data-element-id="inline" style="position:absolute;left:1000px;top:440px;font-size:18px">Inline style</p>`;
 await writeFile(path.join(project,'slides/intro.html'),original+fixture);
 await writeFile(path.join(project,'styles/custom.css'),(await readFile(path.join(project,'styles/custom.css'),'utf8'))+'\n.editor-fixture{position:absolute;left:900px;top:520px;width:180px;height:70px;transform:translate(4px,6px);background:#496b85;padding:10px}.editor-photo{position:absolute;left:1060px;top:180px;width:90px;height:90px}.editor-grid{display:grid;position:absolute;left:850px;top:360px;gap:12px}.editor-grid p{font-size:20px}.editor-blocked{position:absolute;left:1000px;top:400px;font-size:18px!important}');
 await writeFile(path.join(project,'scripts/custom.js'),script+"\nDecksmith.register('intro',{init(slide){const p=document.createElement('p');p.id='runtime-only';p.textContent='Runtime only';p.style.cssText='position:absolute;left:860px;top:470px;font-size:16px';slide.append(p);}});");
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();debugPage=page;page.on('pageerror',e=>console.error('PAGE ERROR',e.message));page.on('console',m=>{if(m.type()==='error')console.error('BROWSER',m.text());});
 // Generate a real valid image fixture through Chromium.
 const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=32;const x=c.getContext('2d');x.fillStyle='#9fcfce';x.fillRect(0,0,32,32);return c.toDataURL();});await writeFile(path.join(project,'assets/photo.png'),Buffer.from(image.split(',')[1],'base64'));
 let server=await start(project);await page.goto(server.url);await page.getByRole('heading',{name:'Slides',exact:true}).waitFor();
 const frame=()=>page.frameLocator('iframe[title="Presentation canvas"]');
 async function select(id){await page.locator('#element-list').selectOption(id);await page.locator('.selection-title').waitFor();await pause(100);}
 async function field(name,value){await page.getByLabel(name,{exact:true}).fill(value);await page.getByLabel(name,{exact:true}).press('Tab');await pause(150);}
 async function save(){await page.getByRole('button',{name:'Save',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.status')?.textContent.includes('Saved'));}
 const api=(endpoint,body,headers={})=>fetch(server.origin+'/api/'+endpoint,{method:body?'POST':'GET',headers:{'x-decksmith-session':server.token,Origin:server.origin,...body?{'Content-Type':'application/json'}:{},...headers},body:body?JSON.stringify(body):undefined});
 await test('opening editor makes no source changes',async()=>{const before=await readFile(path.join(project,'deck.json'));await page.reload();await page.getByRole('heading',{name:'Slides',exact:true}).waitFor();assert.deepEqual(await readFile(path.join(project,'deck.json')),before);assert.equal(await readFile(path.join(project,'slides/intro.html'),'utf8'),original+fixture);});
 await test('actual canvas text, inline emphasis, Unicode and line breaks persist',async()=>{
  await select('headline');await field('Text & inline formatting','Ideas <strong>worth</strong><br>sharing 日本語 🌏');await page.getByRole('button',{name:'Undo',exact:true}).click();await pause(150);assert.match(await frame().locator('[data-slide-id="intro"] [data-element-id="headline"]').innerHTML(),/Good ideas deserve/);await page.getByRole('button',{name:'Redo',exact:true}).click();await pause(150);await save();
  assert.match(await readFile(path.join(project,'slides/intro.html'),'utf8'),/Ideas <strong>worth<\/strong><br>sharing 日本語 🌏/);
  assert.equal(await frame().locator('[data-slide-id="intro"] [data-element-id="headline"] strong').textContent(),'worth');
 });
 await test('typography overrides affect computed CSS and reset reveals authored CSS',async()=>{
  await field('Font size','64');await field('Text color','#efb873');await save();
  assert.equal(await frame().locator('[data-slide-id="intro"] [data-element-id="headline"]').evaluate(el=>getComputedStyle(el).fontSize),'64px');
  assert.equal(await frame().locator('[data-slide-id="intro"] [data-element-id="headline"]').evaluate(el=>getComputedStyle(el).color),'rgb(239, 184, 115)');
  await field('Font size','66');await save();let css=await readFile(path.join(project,'styles/editor.css'),'utf8');assert.equal(css.match(/font-size:/g).length,1);
  await page.getByRole('button',{name:'Reset Font size',exact:true}).click();await pause(150);assert.equal(await frame().locator('[data-slide-id="intro"] [data-element-id="headline"]').evaluate(el=>getComputedStyle(el).fontSize),'88px');await field('Font size','64');await save();
 });
 await test('undo and redo survive Save and restore text and style',async()=>{await page.getByRole('button',{name:'Undo',exact:true}).click();await pause(200);assert.equal(await frame().locator('[data-slide-id="intro"] [data-element-id="headline"]').evaluate(el=>getComputedStyle(el).fontSize),'88px');await save();await page.getByRole('button',{name:'Redo',exact:true}).click();await pause(200);assert.equal(await frame().locator('[data-slide-id="intro"] [data-element-id="headline"]').evaluate(el=>getComputedStyle(el).fontSize),'64px');await save();});
 await test('nested selection, overlay alignment, scaled resize and positioned drag',async()=>{
  await frame().locator('[data-element-id="nested"]').click();await page.waitForFunction(()=>document.querySelector('#element-list').value==='nested');assert.equal(await page.locator('#element-list').inputValue(),'nested');
  await select('positioned');await page.getByLabel('Canvas zoom').selectOption('0.5');
  for(const zoom of ['0.5','0.75']){await page.getByLabel('Canvas zoom').selectOption(zoom);await pause(150);const a=await frame().locator('#editor-selection').boundingBox(),b=await frame().locator('[data-element-id="positioned"]').boundingBox();assert.ok(Math.abs(a.x-b.x)<2&&Math.abs(a.y-b.y)<2&&Math.abs(a.width-b.width)<2);}
  await page.getByLabel('Canvas zoom').selectOption('0.5');const resize=frame().getByRole('button',{name:'Resize se',exact:true});await resize.scrollIntoViewIfNeeded();let box=await resize.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+30,box.y+box.height/2+15,{steps:5});await page.mouse.up();await pause(300);
  assert.equal(await frame().locator('[data-element-id="positioned"]').evaluate(el=>getComputedStyle(el).width),'240px');
  await page.getByRole('button',{name:'Undo',exact:true}).click();await pause(200);assert.equal(await frame().locator('[data-element-id="positioned"]').evaluate(el=>getComputedStyle(el).width),'180px');await page.getByRole('button',{name:'Redo',exact:true}).click();await pause(200);
  const move=frame().getByRole('button',{name:'Move element',exact:true});box=await move.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2-25,box.y+box.height/2-10,{steps:4});await page.mouse.up();await pause(250);
  const geometry=await frame().locator('[data-element-id="positioned"]').evaluate(el=>{const s=getComputedStyle(el);return {left:s.left,top:s.top,transform:s.transform};});assert.deepEqual(geometry,{left:'850px',top:'500px',transform:'matrix(1, 0, 0, 1, 4, 6)'});await save();
 });
 await test('grid spacing preserves display model and runtime nodes are read-only',async()=>{
  await select('grid');await page.getByText('Layout & spacing',{exact:true}).click();await field('Gap','24');assert.equal(await frame().locator('[data-element-id="grid"]').evaluate(el=>getComputedStyle(el).display),'grid');await save();
  await frame().locator('#runtime-only').click();await page.getByText(/This node was generated by a script/).waitFor();assert.equal(await page.locator('#element-list').inputValue(),'');await page.getByRole('button',{name:'Dismiss notice'}).click();
 });
 await test('inline CSS and specificity conflicts are explicit; flex layout is preserved',async()=>{
  await select('inline');assert.equal(await page.getByLabel('Font size',{exact:true}).isDisabled(),true);
  await select('blocked');await field('Font size','30');await page.getByText(/font-size is blocked by authored CSS/).waitFor();assert.equal(await page.getByRole('button',{name:'Save',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Reset Font size',exact:true}).click();await pause(200);
  const container={key:await frame().locator('[data-slide-id="intro"] .title-layout').getAttribute('data-editor-key')};await select(container.key);await page.getByText('Layout & spacing',{exact:true}).click();await field('Gap','28');await save();assert.equal(await frame().locator('[data-slide-id="intro"] .title-layout').evaluate(el=>getComputedStyle(el).display),'flex');assert.match(await readFile(path.join(project,'slides/intro.html'),'utf8'),new RegExp('data-element-id="'+container.key+'"'));
 });
 await test('composition and multiline canvas input do not navigate slides',async()=>{
  await select('headline');await frame().locator('[data-slide-id="intro"] [data-element-id="headline"]').dblclick();const h=frame().locator('[data-slide-id="intro"] [data-element-id="headline"]');await h.dispatchEvent('compositionstart');await h.evaluate(el=>{el.innerHTML='Composing 日本語<br><em>line two</em>';});await h.press('ArrowRight');assert.equal(await page.locator('#element-list').inputValue(),'headline');assert.equal(await page.getByRole('button',{name:'Save',exact:true}).isDisabled(),true);await h.dispatchEvent('compositionend');await page.getByRole('heading',{name:'Properties',exact:true}).click();await pause(300);await save();assert.match(await readFile(path.join(project,'slides/intro.html'),'utf8'),/Composing 日本語<br><em>line two<\/em>/);
 });
 await test('image replacement, alternative text and undo redo use valid local assets',async()=>{
  await select('photo');const second=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=48;c.height=32;c.getContext('2d').fillRect(0,0,48,32);return c.toDataURL();});await page.getByLabel('Replace image',{exact:true}).setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from(second.split(',')[1],'base64')});await pause(200);await page.getByRole('button',{name:'Undo',exact:true}).click();await pause(150);assert.equal(await frame().locator('[data-element-id="photo"]').getAttribute('src'),'assets/photo.png');await page.getByRole('button',{name:'Redo',exact:true}).click();await field('Alternative text','A replacement image 日本語');await save();const html=await readFile(path.join(project,'slides/intro.html'),'utf8');assert.match(html,/assets\/editor-[a-f0-9]{64}\.png/);assert.match(html,/alt="A replacement image 日本語"/);assert.equal(await frame().locator('[data-element-id="photo"]').evaluate(el=>el.naturalWidth),48);
 });
 await test('notes and slide reordering persist, undo and redo',async()=>{
  await field('Notes','Edited speaker notes 日本語\nSecond line');await page.getByRole('button',{name:'Undo',exact:true}).click();await pause(150);assert.match(await page.getByLabel('Notes',{exact:true}).inputValue(),/Introduce the audience/);await page.getByRole('button',{name:'Redo',exact:true}).click();await page.getByRole('button',{name:'Move next up',exact:true}).focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Slide 2: Make the next move'}).dragTo(page.getByRole('button',{name:'Slide 1: Start with an idea'}));await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Redo',exact:true}).click();await save();const m=JSON.parse(await readFile(path.join(project,'deck.json'),'utf8'));assert.deepEqual(m.slides.map(s=>s.id),['next','intro','workflow']);assert.equal(m.slides[1].notes,'Edited speaker notes 日本語\nSecond line');
 });
 await test('close and reopen retain saved source, no overlays in preview',async()=>{
  await page.reload();await page.getByRole('button',{name:'Slide 2: Start with an idea'}).click();await select('headline');assert.equal(await page.getByLabel('Text & inline formatting').inputValue(),'Composing 日本語<br><em>line two</em>');
  server.child.kill('SIGTERM');await new Promise(r=>server.child.once('exit',r));server=await start(project);await page.goto(server.url);await page.getByRole('button',{name:'Slide 2: Start with an idea'}).click();await select('headline');assert.equal(await page.getByLabel('Text & inline formatting').inputValue(),'Composing 日本語<br><em>line two</em>');assert.equal(await frame().locator('[data-slide-id="intro"] [data-element-id="headline"]').evaluate(el=>getComputedStyle(el).fontSize),'64px');await page.getByRole('button',{name:'▷ Preview',exact:true}).click();await frame().locator('#editor-selection').waitFor({state:'hidden'});assert.equal(await frame().locator('#editor-selection').isVisible(),false);await page.getByRole('button',{name:'✎ Edit',exact:true}).click();
 });
 await test('external edits conflict; reload requires explicitly discarding pending edits',async()=>{
  await field('Text & inline formatting','Pending local edit');const p=path.join(project,'slides/next.html');await writeFile(p,'<h1 data-element-id="external">External change</h1>');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Source changed outside this editor.',{exact:true}).waitFor();assert.match(await readFile(p,'utf8'),/External change/);assert.match(await page.getByLabel('Text & inline formatting').inputValue(),/Pending local/);await page.screenshot({path:path.join(screens,'conflict.png')});page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Reload & discard pending edits'}).click();await page.getByText('Source changed outside this editor.',{exact:true}).waitFor({state:'hidden'});await page.getByRole('button',{name:'Slide 2: Start with an idea'}).click();await select('headline');assert.match(await page.getByLabel('Text & inline formatting').inputValue(),/Composing 日本語/);
 });
 await test('authorization, origins, invalid operations and preview write boundary',async()=>{
  assert.equal(await frame().locator('body').evaluate(()=>{try{parent.sessionStorage.getItem('decksmith-session');return false;}catch{return true;}}),true);assert.equal((await fetch(server.origin+'/api/project')).status,401);assert.equal((await api('save',{}, {'x-decksmith-session':'bad'})).status,401);assert.equal((await api('save',{}, {Origin:'https://evil.invalid'})).status,403);const p=await(await api('project')).json();assert.equal((await api('save',{baseline:p.revision,revision:p.revision,operations:[{type:'shell',command:'echo nope'}]})).status,422);assert.equal((await api('save',{baseline:p.revision,revision:p.revision,operations:[{type:'text',slide:'intro',element:'../../etc/passwd',html:'no'}]})).status,422);const preview=await start(project,'dev');assert.equal((await fetch(preview.url)).headers.get('access-control-allow-origin'),null);assert.equal((await fetch(preview.url+'api/save',{method:'POST'})).status,405);preview.child.kill('SIGTERM');
 });
 await test('recoverable preview and network failures retain pending edits',async()=>{
  await field('Text & inline formatting','Ready to share <em>日本語</em><br>Second line');await page.locator('iframe[title="Presentation canvas"]').evaluate(el=>{el.src=el.src;});await frame().locator('[data-slide-id="intro"] [data-element-id="headline"]').filter({hasText:'Ready to share'}).waitFor();await page.route('**/api/save',r=>r.abort());await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByText(/Failed to fetch/).waitFor();assert.match(await page.getByLabel('Text & inline formatting').inputValue(),/Ready to share/);await page.unroute('**/api/save');await save();
 });
 await test('source and authored style preservation',async()=>{assert.deepEqual(await readFile(path.join(project,'slides/next.html')),Buffer.from('<h1 data-element-id="external">External change</h1>'));assert.ok(untouched.length);assert.ok((await readFile(path.join(project,'scripts/custom.js'),'utf8')).startsWith(script.toString()));});
 await test('HTML PNG PDF PPTX exports contain edited content, order and notes',async()=>{
  // Existing checks reject unsupported glyph fonts/overflow as before; use a concise export headline.
  await field('Text & inline formatting','Ready to share <em>clearly.</em><br>Second line');await save();await page.getByLabel('Export format').selectOption('html');await page.getByText(/Exported:/).waitFor({timeout:60000});await page.getByRole('button',{name:'Dismiss notice'}).click();
  for(const format of ['html','pdf','pptx']){const r=run(['export',project,'--format',format,'--json']);assert.equal(r.success,true);if(format==='html'){const html=await readFile(path.join(project,'dist/html/index.html'),'utf8');assert.match(html,/Ready to share/);assert.match(html,/Edited speaker notes/);assert.ok(html.indexOf('data-slide-id="next"')<html.indexOf('data-slide-id="intro"'));for(const marker of ['editor-selection','data-editor-key','x-decksmith-session','decksmith:true'])assert.ok(!html.includes(marker));}if(format==='pdf'){assert.equal(r.artifacts[0].pages,3);assert.equal((await PDFDocument.load(await readFile(r.artifacts[0].path))).getPageCount(),3);}if(format==='pptx'){const zip=await JSZip.loadAsync(await readFile(r.artifacts[0].path));assert.match(await zip.file('ppt/slides/slide2.xml').async('string'),/Ready to share/);assert.match(await zip.file('ppt/notesSlides/notesSlide2.xml').async('string'),/Edited speaker notes/);assert.deepEqual(r.artifacts[0].editability.map(s=>s.slide_id),['next','intro','workflow']);}}
  const r=run(['render',project,'--json']);assert.equal(r.success,true);await cp(path.join(project,'.decksmith/render/slides/intro.png'),path.join(screens,'edited-slide.png'));
 });
 await test('small desktop, window resizing, image-loaded selection and screenshots',async()=>{
  await select('photo');await page.setViewportSize({width:1024,height:800});await page.getByLabel('Canvas zoom').selectOption('fit');await pause(250);const a=await frame().locator('#editor-selection').boundingBox(),b=await frame().locator('[data-element-id="photo"]').boundingBox();assert.ok(Math.abs(a.x-b.x)<2&&Math.abs(a.y-b.y)<2);await page.screenshot({path:path.join(screens,'small-desktop.png')});await page.setViewportSize({width:1440,height:1000});await select('headline');await pause(250);await page.screenshot({path:path.join(screens,'starter-editor.png')});
 });
 await test('selection follows an asynchronously loaded font and reports missing images',async()=>{
  await select('headline');await frame().locator('body').evaluate(async()=>{const face=new FontFace('PresmithTestFace','local("Arial"), local("Liberation Sans"), local("DejaVu Sans")');document.fonts.add(face);window.testFace=face;await face.load();const style=document.createElement('style');style.id='test-font-style';style.textContent='[data-slide-id="intro"] [data-element-id="headline"]{font-family:PresmithTestFace!important}';document.head.append(style);await document.fonts.ready;});await pause(100);
  const a=await frame().locator('#editor-selection').boundingBox(),b=await frame().locator('[data-slide-id="intro"] [data-element-id="headline"]').boundingBox();assert.ok(Math.abs(a.x-b.x)<2&&Math.abs(a.y-b.y)<2&&Math.abs(a.height-b.height)<2);
  await frame().locator('body').evaluate(()=>{document.querySelector('#test-font-style').remove();document.fonts.delete(window.testFace);});
  const photo=frame().locator('[data-element-id="photo"]'),src=await photo.getAttribute('src');await photo.evaluate(el=>{el.src='assets/does-not-exist.png';});await page.getByText(/Image could not load: assets\/does-not-exist.png/).waitFor();await photo.evaluate((el,src)=>{el.src=src;},src);await page.getByRole('button',{name:'Dismiss notice'}).click();
 });
 await test('representative existing product deck renders and supports selection',async()=>{
  const representative=await start(path.join(repo,'examples/product'));const other=await context.newPage();await other.goto(representative.url);await other.getByRole('heading',{name:'Slides',exact:true}).waitFor();await other.locator('#element-list').selectOption('headline');await other.locator('.selection-title').waitFor();await pause(300);await other.screenshot({path:path.join(screens,'product-editor.png')});await other.close();representative.child.kill('SIGTERM');
 });
 await writeFile(path.join(screens,'results.json'),JSON.stringify({tests:results,osIME:'Synthetic composition events only; operating-system IME was not tested',officeImport:'Not tested'},null,2));
 console.log(`${results.length} editor browser checks passed. Screenshots: ${screens}`);
}catch(e){await debugPage?.screenshot({path:path.join(screens,'failure.png')}).catch(()=>{});throw e;}finally{for(const c of children)c.kill('SIGTERM');await browser?.close();await rm(temp,{recursive:true,force:true});}
